[package]
name = "tide-websockets-ext"
version = "0.4.0"
edition = "2018"


[dependencies]
tide-websockets = "0.4"
uuid = { version = "0.8", features = ["v4"] }

async-lock = { version = "2.3", optional = true }
tokio = { version = "1.7", features = ["sync"], optional = true}

[features]
async-std = ["async-lock"]
